# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1e151b75cf19b046a363e21dde72dc955fdd996163f2f6b2fee5a17a9a4a44105203a6c39c7e5c7cceb30fe9e8c5102c89304b308f0b076440204f5d319644

test:
  secret_key_base: c7455b5ead632831b2e23ecd5c4b5ee1449b19cabecb4fe25ae520c73a1291bf05694d10f00b89489a7205451c12ff14a84c30da444cd171ca4af40aeac4d807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
